# Generated by Django 4.1.7 on 2023-02-16 18:30

import datetime
from django.db import migrations, models
import music_api.song_upload


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0007_music_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='length',
        ),
        migrations.RemoveField(
            model_name='music',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='music',
            name='title',
        ),
        migrations.RemoveField(
            model_name='music',
            name='user',
        ),
        migrations.AddField(
            model_name='music',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 21, 30, 26, 869796)),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to=music_api.song_upload.upload_to),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
