# Generated by Django 4.1.7 on 2023-02-17 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0008_remove_music_artist_remove_music_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 19, 19, 14, 799736)),
        ),
    ]
